# Generated by Django 4.1.1 on 2023-07-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="username",),
    ]
