# Generated by Django 4.2.3 on 2023-08-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="img",
            field=models.ImageField(upload_to="category"),
        ),
    ]
