# Generated by Django 4.1.1 on 2023-08-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_userfavorites"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="fullname", new_name="username",
        ),
    ]
