# Generated by Django 4.2.3 on 2023-08-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0004_category_active_recipe_active_user_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="recipe", name="Category",),
        migrations.AddField(
            model_name="recipe",
            name="Category",
            field=models.ManyToManyField(to="recipe.category"),
        ),
    ]
