# Generated by Django 4.2.3 on 2023-08-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0006_ingredient_remove_recipe_ingredients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="IngredientName",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
