# Generated by Django 4.2.3 on 2023-08-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0007_alter_category_title_alter_ingredient_ingredientname"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="desc",
            field=models.TextField(default="null"),
            preserve_default=False,
        ),
    ]
