# Generated by Django 4.1.1 on 2023-08-26 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0008_category_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fav",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="recipe.recipe",
            ),
        ),
    ]
